blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/WwYsQkt3
    about: Join our Discord
  - name: ShapeShift Forum
    url: https://forum.shapeshift.com/
    about: Check out the forum
